name: Change Banner

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  change-banner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Change Banner
        run: |
          files=(image/banner1.gif image/banner2.gif image/banner3.gif image/banner4.gif image/banner5.gif image/banner6.gif)
          random=${files[$RANDOM % ${#files[@]}]}
          cp $random image/banner.gif

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Change banner" || echo "No changes"
          git push
