name: Change Banner

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Change Banner
      run: |
        banners=(images/banner1.gif images/banner2.gif images/banner3.gif images/banner4.gif images/banner5.gif)
        random=$((RANDOM % 5))
        cp ${banners[$random]} images/banner.gif

    - name: Commit
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add images/banner.gif
        git commit -m "Update banner" || exit 0
        git push

        
